language: java
os: osx

script:
- echo "MAVEN_OPTS='-Xmx2G -XX:MaxPermSize=512m'" > ~/.mavenrc

env:
  global:
  - JAVA_HOME=$(/usr/libexec/java_home)
  - MAVEN_OPTS="-Xmx2G -XX:MaxPermSize=512m"

cache:
  directories:
    - $HOME/.m2
